// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WellInsightEngine.Infrastructure.Persistence;

#nullable disable

namespace WellInsightEngine.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251221120838_AdjustDb")]
    partial class AdjustDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.HasKey("Id")
                        .HasName("pk_assets");

                    b.HasIndex("ParentId", "Name")
                        .HasDatabaseName("ix_assets_parent_id_name");

                    b.ToTable("assets", (string)null);
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Parameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<short>("DataType")
                        .HasColumnType("smallint")
                        .HasColumnName("data_type");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_parameters");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_parameters_code");

                    b.ToTable("parameters", (string)null);
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Well", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_wells");

                    b.HasIndex("AssetId")
                        .HasDatabaseName("ix_wells_asset_id");

                    b.HasIndex("ExternalId")
                        .HasDatabaseName("ix_wells_external_id");

                    b.ToTable("wells", (string)null);
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellAction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<short>("Source")
                        .HasColumnType("smallint")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("title");

                    b.Property<Guid>("WellId")
                        .HasColumnType("uuid")
                        .HasColumnName("well_id");

                    b.HasKey("Id")
                        .HasName("pk_well_actions");

                    b.HasIndex("WellId", "Timestamp")
                        .HasDatabaseName("ix_well_actions_well_id_timestamp");

                    b.ToTable("well_actions", (string)null);
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellInsight.WellInsight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("From")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("from");

                    b.Property<string>("Highlights")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("highlights");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<string>("RecommendedActions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("recommended_actions");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.Property<string>("Suspicions")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("suspicions");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("To")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("to");

                    b.Property<Guid>("WellId")
                        .HasColumnType("uuid")
                        .HasColumnName("well_id");

                    b.HasKey("Id")
                        .HasName("pk_well_insights");

                    b.HasIndex("WellId", "CreatedAt")
                        .HasDatabaseName("ix_well_insights_well_id_created_at");

                    b.HasIndex("WellId", "From", "To")
                        .HasDatabaseName("ix_well_insights_well_id_from_to");

                    b.ToTable("well_insights", (string)null);
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellInsightAction", b =>
                {
                    b.Property<Guid>("InsightId")
                        .HasColumnType("uuid")
                        .HasColumnName("insight_id");

                    b.Property<Guid>("WellActionId")
                        .HasColumnType("uuid")
                        .HasColumnName("well_action_id");

                    b.HasKey("InsightId", "WellActionId")
                        .HasName("pk_well_insight_actions");

                    b.HasIndex("WellActionId")
                        .HasDatabaseName("ix_well_insight_actions_well_action_id");

                    b.ToTable("well_insight_actions", (string)null);
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellParameter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ParameterId")
                        .HasColumnType("uuid")
                        .HasColumnName("parameter_id");

                    b.Property<Guid>("WellId")
                        .HasColumnType("uuid")
                        .HasColumnName("well_id");

                    b.HasKey("Id")
                        .HasName("pk_well_parameters");

                    b.HasIndex("ParameterId")
                        .HasDatabaseName("ix_well_parameters_parameter_id");

                    b.HasIndex("WellId", "ParameterId")
                        .IsUnique()
                        .HasDatabaseName("ix_well_parameters_well_id_parameter_id");

                    b.ToTable("well_parameters", (string)null);
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Asset", b =>
                {
                    b.HasOne("WellInsightEngine.Core.Entities.Asset", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_assets_assets_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Well", b =>
                {
                    b.HasOne("WellInsightEngine.Core.Entities.Asset", "Asset")
                        .WithMany("Wells")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wells_assets_asset_id");

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellAction", b =>
                {
                    b.HasOne("WellInsightEngine.Core.Entities.Well", "Well")
                        .WithMany("Actions")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_well_actions_wells_well_id");

                    b.Navigation("Well");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellInsight.WellInsight", b =>
                {
                    b.HasOne("WellInsightEngine.Core.Entities.Well", null)
                        .WithMany()
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_well_insights_wells_well_id");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellInsightAction", b =>
                {
                    b.HasOne("WellInsightEngine.Core.Entities.WellInsight.WellInsight", null)
                        .WithMany()
                        .HasForeignKey("InsightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_well_insight_actions_well_insights_insight_id");

                    b.HasOne("WellInsightEngine.Core.Entities.WellAction", null)
                        .WithMany()
                        .HasForeignKey("WellActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_well_insight_actions_well_actions_well_action_id");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.WellParameter", b =>
                {
                    b.HasOne("WellInsightEngine.Core.Entities.Parameter", "Parameter")
                        .WithMany("Wells")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_well_parameters_parameters_parameter_id");

                    b.HasOne("WellInsightEngine.Core.Entities.Well", "Well")
                        .WithMany("Parameters")
                        .HasForeignKey("WellId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_well_parameters_wells_well_id");

                    b.Navigation("Parameter");

                    b.Navigation("Well");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Asset", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Wells");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Parameter", b =>
                {
                    b.Navigation("Wells");
                });

            modelBuilder.Entity("WellInsightEngine.Core.Entities.Well", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Parameters");
                });
#pragma warning restore 612, 618
        }
    }
}
